<a href="https://colab.research.google.com/github/jose-vera-uchile/Proyecto-Tennis-CC5212/blob/main/Limpieza_Tennis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # Importacion estandar de la libreria Pandas
import numpy  as np # Importacion estandar de la libreria NumPy
from google.colab import files

#Limpieza de datos#

Limpieza de Matches

In [ ]:
url = 'https://media.githubusercontent.com/media/jose-vera-uchile/Proyecto-Tennis-CC5212/main/Raw%20Data/all_matches.csv'
df = pd.read_csv(url)

<ipython-input-3-518efd6351f5>:2: DtypeWarning: Columns (5,8,10,45,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [ ]:
reduced_df=df[['tournament','location','year','player_id', 'opponent_id','sets_won','player_victory','masters']]
reduced_df

,tournament,location,year,player_id,opponent_id,sets_won,player_victory,masters
0,kosice_challenger,Slovakia,2012,adrian-partl,andrej-martin,0.0,f,100
1,kosice_challenger,Slovakia,2012,adrian-partl,jozef-kovalik,2.0,t,100
2,kosice_challenger,Slovakia,2012,agustin-velotti,dominik-hrbaty,0.0,f,100
3,kosice_challenger,Slovakia,2012,agustin-velotti_marcel-felder,andrei-daescu_florin-mergea,1.0,f,100
4,kosice_challenger,Slovakia,2012,alessandro-giannessi,harri-heliovaara,2.0,t,100
...,...,...,...,...,...,...,...,...
4295822,hrt-autumn-cup-2010_itf_juniors0,DEN,2010,tom-georg-hjertonsson,axel-helisten,2.0,t,0
4295823,hrt-autumn-cup-2010_itf_juniors0,DEN,2010,tom-georg-hjertonsson,karl-eirik-wangensten-oye,1.0,f,0
4295824,hrt-autumn-cup-2010_itf_juniors0,DEN,2010,william-baan,callum-poland-smith,2.0,t,0
4295825,hrt-autumn-cup-2010_itf_juniors0,DEN,2010,william-baan,casper-melskens,1.0,f,0
4295826,hrt-autumn-cup-2010_itf_juniors0,DEN,2010,william-baan,jelle-sels,2.0,t,0

In [ ]:
reduced_df2 = reduced_df.loc[reduced_df['masters']>0]
reduced_df2

,tournament,location,year,player_id,opponent_id,sets_won,player_victory,masters
0,kosice_challenger,Slovakia,2012,adrian-partl,andrej-martin,0.0,f,100
1,kosice_challenger,Slovakia,2012,adrian-partl,jozef-kovalik,2.0,t,100
2,kosice_challenger,Slovakia,2012,agustin-velotti,dominik-hrbaty,0.0,f,100
3,kosice_challenger,Slovakia,2012,agustin-velotti_marcel-felder,andrei-daescu_florin-mergea,1.0,f,100
4,kosice_challenger,Slovakia,2012,alessandro-giannessi,harri-heliovaara,2.0,t,100
...,...,...,...,...,...,...,...,...
3824712,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,abhinav-sanjeev-shanmugam,2.0,t,25
3824713,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,bruno-pujol-navarro,2.0,t,25
3824714,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,imanol-lopez-morillo,0.0,f,25
3824715,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,jordi-mas-de-ugarte,2.0,t,25
3824716,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,sergio-gomez-montesa,2.0,t,25

In [ ]:
reduced_df3 = reduced_df2.loc[((reduced_df2['player_victory']=='f')|((reduced_df2['player_victory']=='t')))]
reduced_df3 #Aca tenemos solo las columnas necesarias. y empezamos a quitar nulos. Partimos quitando los partidos que no se sabe quien gano

,tournament,location,year,player_id,opponent_id,sets_won,player_victory,masters
0,kosice_challenger,Slovakia,2012,adrian-partl,andrej-martin,0.0,f,100
1,kosice_challenger,Slovakia,2012,adrian-partl,jozef-kovalik,2.0,t,100
2,kosice_challenger,Slovakia,2012,agustin-velotti,dominik-hrbaty,0.0,f,100
3,kosice_challenger,Slovakia,2012,agustin-velotti_marcel-felder,andrei-daescu_florin-mergea,1.0,f,100
4,kosice_challenger,Slovakia,2012,alessandro-giannessi,harri-heliovaara,2.0,t,100
...,...,...,...,...,...,...,...,...
3824712,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,abhinav-sanjeev-shanmugam,2.0,t,25
3824713,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,bruno-pujol-navarro,2.0,t,25
3824714,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,imanol-lopez-morillo,0.0,f,25
3824715,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,jordi-mas-de-ugarte,2.0,t,25
3824716,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,sergio-gomez-montesa,2.0,t,25

In [ ]:
reduced_df3.dropna(how='all') ##Verificamos que no hayan nulos.

,tournament,location,year,player_id,opponent_id,sets_won,player_victory,masters
0,kosice_challenger,Slovakia,2012,adrian-partl,andrej-martin,0.0,f,100
1,kosice_challenger,Slovakia,2012,adrian-partl,jozef-kovalik,2.0,t,100
2,kosice_challenger,Slovakia,2012,agustin-velotti,dominik-hrbaty,0.0,f,100
3,kosice_challenger,Slovakia,2012,agustin-velotti_marcel-felder,andrei-daescu_florin-mergea,1.0,f,100
4,kosice_challenger,Slovakia,2012,alessandro-giannessi,harri-heliovaara,2.0,t,100
...,...,...,...,...,...,...,...,...
3824712,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,abhinav-sanjeev-shanmugam,2.0,t,25
3824713,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,bruno-pujol-navarro,2.0,t,25
3824714,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,imanol-lopez-morillo,0.0,f,25
3824715,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,jordi-mas-de-ugarte,2.0,t,25
3824716,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,sergio-gomez-montesa,2.0,t,25

In [ ]:
final_df=reduced_df3.loc[((reduced_df3['sets_won']>=0)&(reduced_df3['sets_won']<=3))] ##Finalmente vemos que no existan Outliers, y que todos los valores de sets ganados sean entre 0 y 3
final_df

,tournament,location,year,player_id,opponent_id,sets_won,player_victory,masters
0,kosice_challenger,Slovakia,2012,adrian-partl,andrej-martin,0.0,f,100
1,kosice_challenger,Slovakia,2012,adrian-partl,jozef-kovalik,2.0,t,100
2,kosice_challenger,Slovakia,2012,agustin-velotti,dominik-hrbaty,0.0,f,100
3,kosice_challenger,Slovakia,2012,agustin-velotti_marcel-felder,andrei-daescu_florin-mergea,1.0,f,100
4,kosice_challenger,Slovakia,2012,alessandro-giannessi,harri-heliovaara,2.0,t,100
...,...,...,...,...,...,...,...,...
3824712,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,abhinav-sanjeev-shanmugam,2.0,t,25
3824713,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,bruno-pujol-navarro,2.0,t,25
3824714,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,imanol-lopez-morillo,0.0,f,25
3824715,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,jordi-mas-de-ugarte,2.0,t,25
3824716,spain-f21-futures_itf_procircuit0,ESP,2018,zakhar-trapeznikov,sergio-gomez-montesa,2.0,t,25

Con esto tenemos que nuestro dataset de partidos tiene un total de 3.051.885 filas, por lo que luego de la limpieza el total de partidos se mantiene el minimo de columnas necesarias para el proyecto.

Ahora lo exportamos

In [ ]:
final_df.to_csv('all_matches_clean.csv', index=False, header=False, encoding = 'utf-8')
files.download('all_matches_clean.csv')